### ISSUE TITLE
Mixin Crash on 1.17 Dedicated Server

### ISSUE THREAD

**Issue by Southpaw1496** [aws404/easy-painter#1]
Hi

I was trying to try out EasyPainter on 1.17 (it looks very cool) but when running it on a local server with Fabric server software etc, it crashed. There were no other mods running except it and the Fabric API.

Console output: https://hastebin.com/puhojurahu.properties

## System Specifications
- MacBook Air (M1, 2020)
- macOS Big Sur 11.4
- OpenJDK 16 (from AdoptOpenJDK)

The server runs fine without EasyPainter so I don't think it's to do with having an M1 chip or an incorrect Java installation or anything like that. I tried both the GitHub and Modrinth releases and ensured that it was the 1.17 version, not the 1.16.5 version.

**Comment by aws404** [comment]
Hello,
Could you please try with the mod jar from this release? https://github.com/aws404/easy-painter/releases/tag/1.0.1

**Comment by Southpaw1496** [comment]
Still no joy https://hastebin.com/enevutaweb.properties

**Comment by aws404** [comment]
It appears to be an issue with how I was creating the map textures. Would you mind giving this one a go? https://github.com/aws404/easy-painter/releases/tag/1.0.1

**Comment by Southpaw1496** [comment]
All fixed! Thank you for your help.

**Comment by aws404** [comment]
Brilliant! Ill do a new version.
