### ISSUE TITLE
Player get kicked

### ISSUE THREAD

**Issue by arville27** [aws404/easy-painter#2]
Player gets kicked every time try to enter chunk with painting, I haven't added any custom painting yet.

Logs the server make every time kick player
![image](https://user-images.githubusercontent.com/60413613/121806185-0ad87880-cc79-11eb-97bf-9cddc078c725.png)

**Comment by aws404** [comment]
Thankyou for your report, to help me get to the bottom of the issue would you mind answering in detail these questions:
Have you tried loading custom paintings in the past? 
Do you have any datapacks loaded? If so are they downloaded or created by you? 
If you wouldn't mind running the `/easy_painter clearcache` command and attach the logs of the next server start up.
Thanks!

**Comment by arville27** [comment]
> Have you tried loading custom paintings in the past?

No, I haven't yet tried to load any custom painting

> Do you have any datapacks loaded? If so are they downloaded or created by you?

But I do have data packs on my server, they are from vanillatweaks.net, the list of data pack I used
- durability ping v1.1.0.zip
- more mob heads v2.9.1.zip
- multiplayer sleep v2.6.1.zip
- track raw statistics v1.4.0.zip
- track statistics v1.1.0.zip

> If you wouldn't mind running the /easy_painter clearcache command and attach the logs of the next server start up.

I try running the clearcache command, and it still kicks the player.
Here are the logs of server startup: [Logs](https://pastebin.com/kryJktTn)

I'm sorry for my bad english

**Comment by aws404** [comment]
That is fine, it seems the errors are not directly related to the mod, are you be able to send your world file? Preferably in a zip file.
Thanks.

**Comment by arville27** [comment]
I have set up a temporary site for the world file, as soon as your next reply this site will go down ([world.zip](https://minecraft.arville.net/world.zip))

Extra information, coordinate of the chunk that causing the problem is -500 64 2065

**Comment by aws404** [comment]
After investigating the issue, it appears to have been a bug with a dependency, after updating the dependencies I can no longer reproduce the issue.

Thankyou for your report!

Please find the updated mod here:
* MR: https://modrinth.com/mod/easy_painter/version/Seg3zLtt
* GH: https://github.com/aws404/easy-painter/releases/tag/1.0.2
